<img src="https://github.com/pavlek358/DSB-Unit-02/blob/main/assets/ga-logo.png?raw=1" style="float: left; margin: 20px; height: 55px">

# Visualizing trends

---

### About
Understand how to create charts within `pandas` using the `.plot()` method.

### Learning Objectives
- Chart dates in `pandas`
- Create line charts with `matplotlib`

### Notebook Guide
- Scenario
- Working with dates in `pandas`
- Now You Try!
- Conclusions and Takeaways

# Scenario

You're an analyst working for CoolBricks - a new toy company who wants to compete with LEGO by producing their own bricks and sets. To better understand what kind of sets to create and at what price points, you are tasked with analyzing LEGO's catalogue over time.

The data comes from Kaggle: [https://www.kaggle.com/datasets/alexracape/lego-sets-and-prices-over-time](https://www.kaggle.com/datasets/alexracape/lego-sets-and-prices-over-time)

We are going to use `pandas` to read this data and `matplotlib` to create plots.

Our research question is: ***How have the number of products changed over time?***

# Working with dates in `pandas`
---

In [4]:
import pandas as pd

lego_df = pd.read_csv('https://raw.githubusercontent.com/pavlek358/DSB-Unit-02/refs/heads/main/data/lego.csv')

Let's look at the data

In [7]:
pd.to_datetime(lego_df["Year"], format="%Y")

0       1975-01-01
1       1975-01-01
2       1975-01-01
3       1975-01-01
4       1975-01-01
           ...
14931   2023-01-01
14932   2023-01-01
14933   2023-01-01
14934   2023-01-01
14935   2023-01-01
Name: Year, Length: 14936, dtype: datetime64[ns]

We have a "year" column which is an integer, but it could also be a date!

To convert a string to a date we can use the `pandas` `.to_datetime()` method, where we can also specify the format of the date. *See [http://strftime.org/](http://strftime.org/) for more details about datetime formats in Python.*

If we don't specify the format, we get this:

In [16]:
lego_df["year_date"] = pd.to_datetime(lego_df["Year"], format="%Y")
lego_df["year_date"]

0       1975-01-01
1       1975-01-01
2       1975-01-01
3       1975-01-01
4       1975-01-01
           ...
14931   2023-01-01
14932   2023-01-01
14933   2023-01-01
14934   2023-01-01
14935   2023-01-01
Name: year_date, Length: 14936, dtype: datetime64[ns]

Let's tell `pandas` that the string actually represents the year (and `pandas` will come up with defaults for the month and day)

In [17]:
# 1. Convert Year into a datetime
lego_df["year_date"] = pd.to_datetime(lego_df["Year"], format="%Y")

# 2. Extract the year from the datetime
lego_df["year_date"].dt.year

0        1975
1        1975
2        1975
3        1975
4        1975
         ...
14931    2023
14932    2023
14933    2023
14934    2023
14935    2023
Name: year_date, Length: 14936, dtype: int32

Great, let's save the "date version" as a new column

In [18]:
lego_df["year_date"].dt.year

0        1975
1        1975
2        1975
3        1975
4        1975
         ...
14931    2023
14932    2023
14933    2023
14934    2023
14935    2023
Name: year_date, Length: 14936, dtype: int32

Now, we can access date components with the `.dt` accessor

In [19]:
lego_df["year_date"].dt.year

0        1975
1        1975
2        1975
3        1975
4        1975
         ...
14931    2023
14932    2023
14933    2023
14934    2023
14935    2023
Name: year_date, Length: 14936, dtype: int32

And we have two ways of calculating "products per year". The first is to use the original `Year` column:

In [20]:
lego_df["year_date"].dt.month
lego_df["year_date"].dt.day
lego_df["year_date"].dt.day_name()
lego_df["year_date"].dt.quarter

0        1
1        1
2        1
3        1
4        1
        ..
14931    1
14932    1
14933    1
14934    1
14935    1
Name: year_date, Length: 14936, dtype: int32

Or we can set the `index` of the `DataFrame` to the date column and use `resample` (which is like `groupby` but specifically for dates)

In [21]:
lego_df.groupby("Year").size()

Year
1975     45
1976     76
1977     74
1978     87
1979     90
1980    117
1981     74
1982     73
1983     76
1984     84
1985    141
1986    152
1987    200
1988     79
1989    146
1990    129
1991    147
1992    112
1993    168
1994    154
1995    172
1996    213
1997    264
1998    383
1999    352
2000    384
2001    409
2002    449
2003    426
2004    419
2005    395
2006    467
2007    449
2008    443
2009    487
2010    500
2011    500
2012    500
2013    500
2014    500
2015    500
2016    500
2017    500
2018    500
2019    500
2020    500
2021    500
2022    500
2023    500
dtype: int64

In [25]:
lego_df.resample("YE").size()

TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'RangeIndex'

The advantage of `resample` is we get a `Series` that already has a temporal index. This helps with creating line charts with better defaults, for example.

To create a line chart from this data, we can simply call `.plot()` (the default type is a line chart)

In [23]:
lego_df.resample("YE").size().plot()

TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'RangeIndex'

As with most plots, we can set some additional values

In [ ]:
lego.df

# Now You Try!
----

1. Create a line chart showing the _**average product retail price**_ over time.

What do you conclude?

How can you improve the chart?

Looks like there is a lot of missing data before the year 2000. We could use that as a cutoff and only visualize data after that year.

2. *BONUS:* Create a new column to calculate the _**decade**_ a product was released. Then calculate the _**average number of pieces per product**_ per decade and plot it as a line chart.

# Conclusions and Takeaways

- `pandas` lets us convert strings to dates with `to_datetime()`
- Once a column is a date, more functionality is available to us
- One use case of date columns is the easier creation of line charts